### PR TITLE
removed noble-mac version spec

### PR DESCRIPTION
**Pull request by matthewsibigtroth**
removed version since git checkout was hanging on the 0.0.4

### CODE REVIEW

**Comment by happycodelucky** [comment]
I've been using `@abandonware/noble` in other projects. I need to spend some time updating this package and republishing.

**Comment by matthewsibigtroth** [comment]
Thanks Paul. Great library and nice work! Btw, that PR was an accident in
case it wasn't obvious, ha. Cheers!

**Comment by happycodelucky** [comment]
I figured :)

Thanks! The only thing annoying is not being able to reset or change the
modulation wheel CC. I found a dev at Teenage Engineering but couldn’t
offer the right command to reset.

I have a similar package for Nuimo.

**Comment by happycodelucky** [comment]
I just pushed v0.2.0 with all dependencies upgraded

**Comment by matthewsibigtroth** [comment]
Oh! Amazing turnaround. Thank you! 👍

**Pull request closed without merging**
